alternate: Artorias's Life

# Whether to show the loading cat
loader:
  start: true # When entering the page
  switch: false # When switching to another page

menu:
  home: / || home
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  about: /about/ || user
  # friends: /friends/ || heart
  # links: /links/ || magic
  
# Social Links
# Usage: `Key: permalink || icon || color`
# Key is the link label showing to end users.
# Value before `||` delimiter is the target permalink,
# secend value is the name of Font icon.
social:
  github: https://github.com/ArtoriasLife || github || "#191717"
  #google: https://plus.google.com/yourname || google
  #twitter: https://twitter.com/yourname || twitter || "#00aff0"
  #zhihu: https://www.zhihu.com/people/yourname || zhihu || "#1e88e5"
  music: https://music.163.com/#/user/home?id=yourid || cloud-music || "#e60026"
  #weibo: https://weibo.com/yourname || weibo || "#ea716e"
  about: https://about.me/yourname || address-card || "#3b5998"
  email: mailto:yourname@mail.com || envelope || "#55acd5"
  facebook: https://www.facebook.com/yourname || facebook
  stackoverflow: https://stackoverflow.com/yourname || stack-overflow
  youtube: https://youtube.com/yourname || youtube
  instagram: https://instagram.com/yourname || instagram
  skype: skype:yourname?call|chat || skype
  #douban: https://www.douban.com/people/yourname/ || douban
  
footer:
  # Specify the date when the site was setup. If not defined, current year will be used.
  since: 2020
  icon:
    name: star rotate
    # Change the color of icon, using Hex Code.
    color: "#01847f"
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  count: true
  powered: true
  
post:
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  count: true
  
  
# Comments
# Valine
# For more information: https://github.com/amehime/MiniValine
valine:
  appId: #Your_appId
  appKey: #Your_appkey
  placeholder: ヽ(○´∀`)ﾉ♪ # Comment box placeholder
  avatar: mp # Gravatar style : mp, identicon, monsterid, wavatar, robohash, retro
  pageSize: 10 # Pagination size
  lang: en
  visitor: true # Article reading statistic
  NoRecordIP: false # Whether to record the commenter IP
  serverURLs: # When the custom domain name is enabled, fill it in here (it will be detected automatically by default, no need to fill in)
  powerMode: true
  tagMeta:
    visitor: 新朋友
    master: 主人
    friend: 小伙伴
    investor: 金主粑粑
  tagColor:
    master: "var(--color-orange)"
    friend: "var(--color-aqua)"
    investor: "var(--color-pink)"
  tagMember:
    master:
      # - hash of master@email.com
      # - hash of master2@email.com
    friend:
      # - hash of friend@email.com
      # - hash of friend2@email.com
    investor:
      # - hash of investor1@email.com


# bgm
audio:
  - title: Silence
    list:
     - https://music.163.com/#/playlist?id=5382015259
     - https://music.163.com/#/playlist?id=5302425773
  # - title: 列表2
  #   list:
  #    - https://music.163.com/#/playlist?id=2031842656
  
# random image api
image_server: # "https://acg.xydwz.cn/api/api.php"